#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "game-service.fullname" . }}
#  sessionAffinity: ClientIP
